# Configuration for Cloudflare Pages deployment
name = "unichat-dev"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-07-01"
pages_build_output_dir = "./build"
send_metrics = false

[build]
command = """
pnpm install && \
python -m pip install --upgrade pip setuptools wheel && \
python -m pip install packaging==24.1 && \
pnpm run pyodide:fetch && \
vite build
"""

[env.production]
NODE_VERSION = "18.17.1"
NPM_VERSION = "9.6.7"
PNPM_VERSION = "9.15.1"
PYTHON_VERSION = "3.11" 